sahana/eden

modules/s3/s3widgets.py
http://127.0.0.1:8000/eden/req/req/1/req_item --> Add Item to request , Autocomplete for Item field not working before. (Giving link of localhost because demo is not working ;) )
=> [Fix]: Representation of item name in autocomplete widget

modules/s3/s3codecs/pdf.py, modules/tests/run_pdf_tests.py, modules/tests/test_pdf_1.pdf, modules/tests/test_pdf_2.pdf
I plan to re-factor the pdf codec so that styling will be easier. To ensure that the change can be properly tested I have added this test along with two sample files from the test. Currently the test will consist of manually verifying the file created matched the file on the repository. Later an automatic diff could be added for this test.
=> Minor changes with pdf codec and a small eyeball test for planned enhancment

modules/s3/s3codecs/xls.py
As the title says, it's a <b>really</b> small syntax error, but it appears to break exporting for all report_groupby resources.
=> fix for really small syntax error for xls codec

modules/s3/s3codecs/xls.py, modules/s3cfg.py, modules/templates/default/config.py
Previously, a deployment would have to uncomment/comment multiple non-adjacent lines in the codec itself if they wanted to add a title row to xls_exports. This change allows deployments to do so by specifying "settings.base.xls_title_row = True" in 000_config.py.
Summary:
- The codec in modules/s3/s3codecs/xls.py adds a title row if it is specified in the deployment settings.
- Added function in modules/s3cfg.py to access this setting.
Pull request is currently two commits because I don't know whether you want the commented option in modules/templates/000_config.py or not. The first commit adds the title row code to the codec and creates the corresponding function in s3cfg.py. The second commit adds commented lines to 000_config.py; the user would simply uncomment the line if they want to …
=> Add option to include a title row in xls exports

controllers/pr.py, modules/s3cfg.py
Fixes usage of `settings.pr.contacts_tabs`
1. Modules PR and HRM look up labels by keys `"public_contacts"` and `"private_contacts"` but in `get_pr_contacts_tab_label()` defaults, there are only `"public"` and `"private"` which don't seem to be used anywhere (possibly some confusion with default values in `get_pr_contacts_tabs()`)
2. PR module controler checks if the private tab should be added, but assigns label for public (likely overlooked after copy-paste)
=> PR, HRM & cfg: Fix Public / Private Contacts labels

modules/s3menus.py
Tiny little PR to show *Resource Types* in Organisation menu. Allows browsing, editing, deletion etc.
=> ORG: Add "Resource Types" to Organisation menu

static/scripts/simile/timeline/scripts/l10n/cs/labellers.js, static/scripts/simile/timeline/scripts/l10n/vi/labellers.js
I'm aware that Simile widget is a 3rd party component abandoned since 2015 (at least the version which SE uses is), so it would be for the best to upgrade it completely. For the time being I'm at lest pushing this PR to fix the timeline labels by changing the encoding from ISO-8859-2 to UTF-8.
=> Simile Timeline: Fix encoding for cs and vi labels

modules/s3/s3crud.py
PR based on issue #1388. Changes *custom_submit* from tuple to list and also makes S3CRUD always convert it to list, which allows `settings.ui.interim_save` to modify the *custom_submit*.
The S3CRUD conversion in commit [101ff4d](https://github.com/trendspotter/eden/commit/101ff4d4c8557c6a8ef9b23ba291d692ce1a6d1b) might not be needed anymore as *custom_submit* is only in CAP module and CRMT template, so feel free to cherry-pick whatever seems the best.
=> S3CRUD: Allow immutable custom_submits to have interim save button

modules/s3/s3gis.py
Found out why can't I find any features around me as mentioned in [this comment for #1378](https://github.com/sahana/eden/issues/1378#issuecomment-331710389). The latitude and longitude is swapped in `get_features_in_radius()` SQL query.
=> GIS: Fix swapped lat/lon in WKT for get_features_in_radius()

static/formats/s3csv/edu/school.csv, static/formats/s3csv/edu/school.xsl
Adds the possibility to define school capacity and contact in imports, since they exist in the *Create* form.
I understand the idea of imports and validation conceptually, but not yet implementation-wise, so I hope I got this one right. (Tests suggest that I did.)
=> Edu: Add school capacity and contact to XSLT and CSV

modules/s3db/dvi.py
A bug exists where creating a *Recovery request* and subsequently linking the request to a *Dead body* throws following error 500 while visiting `/eden/dvi/body/1/read`
```
File "/srv/sahana/gluon/restricted.py", line 227, in restricted
exec ccode in environment
File "/srv/sahana/applications/eden/controllers/dvi.py", line 289, in <module>
File "/srv/sahana/gluon/globals.py", line 417, in <lambda>
File "/srv/sahana/applications/eden/controllers/dvi.py", line 153, in body
return s3_rest_controller(rheader=rheader)
File "/srv/sahana/applications/eden/models/00_utils.py", line 243, in s3_rest_controller
output = r(**attr)
File "applications/eden/modules/s3/s3rest.py", line 691, in __call__
output = self.resource.crud(self, …
```
=> DVI: Fix recreq represent

controllers/default.py
This PR fixes the problem when *dataTable* with organisation listing located on home page did not paginate properly with more that 40 organisation records.
Cause:
The pagination sends requests with GET variables `start` and `limit` whereas the code tried to read `displayStart` and `pageLength` which didn't exist, thus always fell back to the default values.
=> Fix pagination for Organisation listing on homepage

views/cr/shelter_create.html, views/cr/shelter_list_filter.html
Cosmetic issue. When `settings.ui.interim_save = True`, the message *"The next screen will allow you to..."* in shelter creation form is displayed twice (once per submit button). This PR forces the responsible jQuery snippets to take into account only the first submit button.
=> Show shelter workflow message only once when interim_save is enabled

modules/s3db/patient.py
Patient module allows to enter *Home City*, however the requirement specifies that L2 location needs to be entered, which corresponds to *County / District* level. Moreover, this is the only place (except from GIS module itself) where the requirements for specific level are imposed directly in *IS_LOCATION()*. Additionally, the *S3LocationAutocompleteWidget* doesn't seem to support the level restriction as it autocompletes all levels and not just L2.
=> Unrestrict patient's home location

controllers/delphi.py, modules/s3db/delphi.py
Unlike most of the other strings, these particular H4 headings cannot be translated out-of-the-box.
Additionally, the *Problems* table contains a *Created By* column, which was missing a label override allowing for translation.
=> Make Delphi H4 and table headers translatable

modules/s3/s3merge.py
I added a tabindex attribute to the widgets being created.
Tab should now go through every attribute of one record, and then the same loop for the other record.
=> fixed bug#1243 Record Tab Merger

modules/s3cfg.py
This PR amends da7b7d0.
When `settings.auth.registration_organisation_default` is set to a string and the organization doesn't exist yet, login/sign-in page fails with error 500 due to undefined variable.
```
File "/srv/web2py/applications/eden/controllers/default.py", line 1558, in <module>
File "/srv/web2py/gluon/globals.py", line 419, in <lambda>
File "/srv/web2py/applications/eden/controllers/default.py", line 547, in user
auth.configure_user_fields()
File "applications/eden/modules/s3/s3aaa.py", line 1814, in configure_user_fields
organisation_id.default = deployment_settings.get_auth_registration_organisation_default()
File …
```
=> Fix creation of registration_organisation_default

views/delphi/results.html
This PR makes translation possible for one string in Delphi module I've missed in PR #1464
=> Add missing T() for Delphi results view

models/zzz_1st_run.py
The gis_hierarchy is required for the app to be functional. This
modifies the first run script to check that a gis_hiearchy has been
populated. If not, then the default gis_hierarchy is loaded.
Fixes #1502
=> Prepopulate the gis_hiearchy with default values if none are provided

languages/bs.py, languages/fa.py, languages/it.py, languages/km.py, languages/my.py, languages/ne.py, languages/prs.py, languages/ps.py, modules/s3/s3gis.py, modules/unit_tests/s3/s3gis.py, static/themes/default/widgets.css
Displaying the error in the map component allows the rest of the webpage
to load normally and removes an unsafe redirect from a lower level
function, as suggested in #1513.
This commit also moves the instantiation of the loader component into
the `_setup()` method after we've fetched the config, to ensure that the
error message doesn't appear with a permanent loading icon above it.
=> Display error in map component if there is no GIS config

modules/s3/s3aaa.py, modules/s3db/auth.py, modules/templates/CCC/controllers.py, modules/unit_tests/s3/s3aaa.py
Addresses #1517
Moves the `auth_user_temp` table from db to s3db to prevent it from
unnecessarily being loaded on every request.
Includes a basic unit test, but I also manually tested registering a
user, approving the user, disabling the user, and re-approving the user
with the CCC template.
=> Refactor `auth_user_temp` into an S3Model class

modules/nameparser/parser.py, modules/s3/s3gis.py, modules/s3/s3import.py, modules/s3/s3resource.py
Comparing string and numerical literals using `is` and `is not` operators causes python 3.8 to emit SyntaxWarning, such as the ones below. This PR aims to fix the comparisons. Relevant issue on python bug tracker is https://bugs.python.org/issue34850
```
/srv/web2py/applications/eden/modules/s3/s3resource.py:3928: SyntaxWarning: "is" with a literal. Did you mean "=="?
if id_column is 0:
/srv/web2py/applications/eden/modules/s3/s3gis.py:1350: SyntaxWarning: "is" with a literal. Did you mean "=="?
elif config_id is 0:
/srv/web2py/applications/eden/modules/s3/s3import.py:1203: SyntaxWarning: "is not" with a literal. Did you mean "!="?
elif totals[1] is not 0:
/srv/web2py/applications/eden/modules/s3/s3import.py:1205: SyntaxWarning: "is not" with a literal. Did you mean "!="?
elif totals[2] …
```
=> Use == and != when comparing literals to fix python3.8 SyntaxWarning

modules/s3/s3translate.py, optional_requirements.txt
This PR finishes the work done in #1468 also for Pootle files.
- Fixes a variable forgotten during refactoring (line 810)
- CSV files need to be always handled as text
- _csv2po_ is imported and handled as python module instead of calling an external binary. This has several advantages
- _csv2po_ binary is provided by _translate-toolkit_ python package. If we have the package, we don't need to run an extra process for it. Calling binaries is expensive.
- subprocess.call() with shell=True (as required on Windows) requires the command to be a string, not list. This would require escaping for filename params (can be done via pipes.escape() on py<=2.6 and shlex.escape() on py>=2.7), but would uglify the code even further.
- Errors in processing are obvious. E.g. when the _translate-toolkit_ …
=> Fix S3Translate Pootle export

controllers/admin.py, modules/s3/s3translate.py
This PR fixes line iteration errors brought in in commits done in order to fix #1468.
Without the changes, the translations from HTML and JS files are not exported. The iteration logic remained from before the fix, when the for-loop has been run on the file object, which is not suitable now, when the file is fully read beforehand. Introducing `splitlines()` helps to solve that problem, along with line-ending sanitation, however it needed to be reflected in `merge_user_strings_file()`, hence the extra line-ending write (`\n` as recommended on https://docs.python.org/2/library/os.html?highlight=linesep#os.linesep )
=> Fix HTML+JS files translation export

modules/s3db/req.py
This PR fixes an exception when a person is committed to the request.
Steps to reproduce:
1. Go to *Organizations* -> *Facilities*
2. Create a facility filling in only the required fields (name)
3. Go to *Requests* -> *Requests* -> *Create*
4. Create a request for *People* filling in only the required fields (facility)
5. Go to *Requests* -> *Requests*
6. Click on *Commit* next to the previously created request and confirm the alert
7. Click on *Save Changes*
```
File "/srv/web2py/applications/eden/controllers/req.py", line 1935, in <module>
File "/srv/web2py/gluon/globals.py", line 429, in <lambda>
File …
```
=> req: Fix crash when person without skill is assigned

modules/s3db/deploy.py
This PR crudely fixes missing gluon html classes imports in *Deployment* module, which cause a crash on alert creation.
Steps to reproduce:
1. Go to *Deployments* -> *Missions* -> *Create*
2. Create a mission filling in required fields (name)
3. Click on *Create Alert* in the mission
4. Create an alert filling in required fields (message)
5. Observe error after clicking on *Save*
```
File "/srv/web2py/applications/eden/controllers/deploy.py", line 1001, in <module>
File "/srv/web2py/gluon/globals.py", line 429, in <lambda>
File "/srv/web2py/applications/eden/controllers/deploy.py", line 641, in alert
return s3_rest_controller(rheader = …
```
=> Deploy: Fix missing gluon.html imports

modules/s3db/gis.py
This PR fixes map marker image upload which otherwise fails with
```
File "/srv/web2py/applications/eden/controllers/gis.py", line 3937, in <module>
File "/srv/web2py/gluon/globals.py", line 429, in <lambda>
File "/srv/web2py/applications/eden/controllers/gis.py", line 1456, in marker
return s3_rest_controller(rheader=s3db.gis_rheader)
File "/srv/web2py/applications/eden/models/00_utils.py", line 245, in s3_rest_controller
output = r(**attr)
File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 691, in __call__
output = self.resource.crud(self, **attr)
File "/srv/web2py/applications/eden/modules/s3/s3rest.py", line 1775, in …
```
=> Fix map marker image upload

Dockerfile
This will help reduce the Docker image size, and speed up the image pull/push process.
=> Clean up apt cache/temp files in Dockerfile

Dockerfile
Ubuntu 14.10 was EOL-ed for years, currently the Ubuntu version being
used on Travis CI by eden is 18.04(bionic), should align the versions.
Also set DEBIAN_FRONTEND=noninteractive to prevent interactive apt-get
dialog from tzdata package after upgraded to Ubuntu 18.04.
=> Update Docker base image ubuntu to 18.04

Dockerfile
Dockerfile best practices reference:
- https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy
> For other items (files, directories) that do not require `ADD`’s tar
> auto-extraction capability, you should always use `COPY`.
=> Use COPY instead of ADD instruction in Dockerfile

modules/s3db/inv.py
Navigating to `/eden/inv/send` and `eden/inv/recv` with `settings.ui.export_formats` left commented in `config.py` currently fails with the following error
```pytb
File "/srv/web2py/applications/eden/controllers/inv.py", line 1469, in <module>
File "/srv/web2py/gluon/globals.py", line 430, in <lambda>
File "/srv/web2py/applications/eden/controllers/inv.py", line 435, in recv
return inv_recv_controller()
File "/srv/web2py/applications/eden/modules/s3db/inv.py", line 9894, in inv_recv_controller
return current.rest_controller("inv", "recv",
File "/srv/web2py/applications/eden/models/00_utils.py", line 268, in s3_rest_controller
output = …
```
=> Inv: Avoid NoneType error with default settings.ui.export_formats
