sahana/eden

- controllers/project.py
I still think the fieldname of project_activity should be changed to start_date instead of date(consistency!)
> start_date and end_date widget working for project/activity

- controllers/survey.py
- modules/s3db/survey.py
- modules/s3db/tour.py
I'll complete another 3 re-writes once you have your views on this!
This function takes care of download button in this : http://demo.eden.sahanafoundation.org/eden/survey/template/1/translate
> Re-write using S3Method handler

- modules/templates/SSF/config.py
Filtering doesn't work with some fields here.
http://sunflower.sahanafoundation.org/eden/project/project/1/task 
For eg: milestone.
> SSF Bug Fix

- modules/templates/SSF/config.py
- modules/templates/SSF/views/msg/notify_email_html.html
- static/themes/SSF/js/role.js
- Prevent User from receiving notifications for his/her comments.
- (Sunflower - 'Watch') Bug fix - I assumed the url to be of the form "task/id" but it can also be  "task?task.uid=urn:uuid=...."
> SSF Tweaks

- modules/s3/s3fields.py
- modules/s3/s3widgets.py
- modules/s3db/hrm.py
- static/scripts/S3/s3.datepicker.js
Hey,
@nursix Please Review
@flavour Removed the seperate js file and put in s3.datepicker.js
> Automation of end-date based on start-date

- modules/s3/s3fields.py
- modules/s3/s3widgets.py
- modules/s3db/hrm.py
- static/scripts/S3/s3.datepicker.js
1) Created an option for explicit default in s3.end_date_interval
2) Using S3.start_end_date in hrm_credential
> Option for s3.end_date_interval and other minor enchancement

- modules/s3db/asset.py
- modules/s3db/budget.py
- modules/s3db/deploy.py
- modules/s3db/hrm.py
- modules/s3db/member.py
- modules/s3db/pr.py
- modules/s3db/project.py
- modules/s3db/stats.py
- modules/s3db/supply.py
- modules/s3db/survey.py
- modules/s3db/vulnerability.py
- static/scripts/S3/s3.datepicker.js
Please let me know which ones need explicit default.
Any other suggestions?
> Deployment Settings for interval in S3.end_date_interval

- modules/s3/s3aaa.py
The register form doesn't work with "foundation_inline" as the formstyle. So, To-Do = Fix ;)
> Register Bug-fix

- modules/s3db/project.py
- modules/templates/SSF/config.py
- static/formats/rss/modules/project.xsl
- static/themes/SSF/js/role.js
- Comments rss - template-specific ?
- Task author should automatically be subscribed to task updates
> SSF: Comments RSS, Subscribe task author to updates

- controllers/scenario.py
- modules/s3db/scenario.py
Add filter widgets for components of scenario.
> [Scenario]: Minor Tweaks

- controllers/asset.py
- controllers/inv.py
- modules/s3cfg.py
- modules/s3db/org.py
- modules/s3menus.py
- modules/templates/IFRC/config.py
- modules/templates/default/config.py
* Default "index" resources to summary method
* Adding Report Options & Defaults
* Removing extra embedded table if there is no Org Logo (return "")
* Menus check if skills and certificates are enabled
(introspect project menus, list_fields, filters and report_options have been removed as these will now have to be re-implemented on updated code)
> Misc Changes

- modules/s3cfg.py
- modules/s3db/cap.py
- modules/templates/000_config.py
default source configuration
expire offset configuration
is_template is true for the one derived from alert template
> default CAP identifier,source and expire offset configuration

- modules/s3/s3codecs/xls.py
http://eden.sahanafoundation.org/ticket/1630
Easy workaround for the xlwt export limit by creating a multi-sheet workbook. Done by creating an array of sheets with size determined by the amount of rows being exported.
TODO: redo the code that allows the user to add a title row (currently doesn't work anymore, though the fix should be simple).
> Fix for bug #1630 - XLS EXPORTS LIMITED TO 65536 ROWS

- static/formats/rss/export.xsl
- static/formats/rss/modules/cap.xsl
> CAP RSS Feed

- controllers/cap.py
- modules/s3cfg.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/config.py
> submit for approval and approve/reject alert

- controllers/cap.py
- modules/s3db/cap.py
> cap_area template form revised/predefined cap_area based on event_type

- controllers/cap.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/config.py
> cap_area_location inlined

- modules/s3db/cap.py
- static/formats/cap/export.xsl
> fixed export.xsl and minor changes

- modules/s3db/cap.py
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/controllers.py
- modules/templates/SAMBRO/views/msg/notify_email.html
- modules/templates/SAMBRO/views/msg/notify_sms.html
> SAMBRO email and sms subscriptions

- modules/templates/SAMBRO/tasks.cfg
> SAMBRO: prepopulate event_type

- modules/s3db/cap.py
> copy the cap_info record

- controllers/cap.py
- modules/s3cfg.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/auth_roles.csv
- modules/templates/SAMBRO/config.py
> cap_area_name: localisation of cap_area name

- modules/s3db/cap.py
> using S3Deduplicate got cap_area_name

- controllers/cap.py
- modules/s3db/cap.py
- static/formats/cap/export.xsl
- static/formats/cap/import.xsl
> Added Event as a new field - text

- modules/templates/SAMBRO/views/msg/notify_sms.html
> SAMBRO: SMS Bug Fix

- controllers/project.py
Ajax call breaks when submitting a record for staff.
> project_Details bug fix

- controllers/cap.py
- modules/s3/s3crud.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/menus.py
> CAP: minor correction

- modules/templates/000_config.py
> SAMBRO: OID fix

- modules/templates/SAMBRO/views/index.html
> SAMBRO: show/hide the filter options; remove the word alerts

- controllers/cap.py
- modules/s3db/cap.py
> CAP: Added resource segment to the template/SAMBRO: rheader name changed for template

- controllers/cap.py
- modules/s3db/cap.py
> CAP: for cap_area auto assign the info_if if only one record is present

- controllers/cap.py
> CAP: selecting first row

- controllers/cap.py
- modules/s3db/cap.py
> SAMBRO: update info_id for the resources from template

- modules/s3db/cap.py
> SAMBRO: add trailing commas

- modules/templates/SAMBRO/menus.py
> SAMBRO: menus

- modules/templates/SAMBRO/Demo/Myanmar-Flood-MultiLanguage.xml
- modules/templates/SAMBRO/Demo/Myanmar-Tsunami-MultiLanguage.xml
- modules/templates/SAMBRO/Demo/tasks.cfg
> SAMBRO: Myanmar Alert Prepop

- modules/templates/SAMBRO/Demo/Maldives-Tsunami-MultiLanguage.xml
- modules/templates/SAMBRO/Demo/tasks.cfg
> SAMBRO: Maldives Alert Prepop

- modules/s3db/cap.py
> SAMBRO:minor tweaks

- controllers/cap.py
- modules/s3db/cap.py
> CAP: More filter widgets

- controllers/cap.py
- modules/s3db/cap.py
> CAP Predefined Area: Add multiple area for multiple info

- modules/s3db/cap.py
- modules/templates/SAMBRO/Demo/cap_warning_priority.csv
- modules/templates/SAMBRO/config.py
- static/scripts/S3/s3.cap.js
> SAMBRO: color coded cap area

- controllers/cap.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/menus.py
- views/cap/index.html
> CAP: give the priority color to headline + whitespaces removal

- controllers/cap.py
- modules/s3db/cap.py
> CAP: More Help tooltip

- controllers/cap.py
- modules/s3db/cap.py
- modules/s3menus.py
- modules/templates/SAMBRO/auth_roles.csv
- modules/templates/SAMBRO/menus.py
> CAP:tweaks

- controllers/cap.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/controllers.py
- modules/templates/SAMBRO/menus.py
> SAMBRO: datalist modifications

- modules/templates/SAMBRO/controllers.py
- static/themes/SAMBRO/js/homepage.js
- static/themes/SAMBRO/style.css
> SAMBRO: active alert datalist

- static/scripts/S3/s3.cap.js
> CAP: Fix for jQuery warning

- controllers/cap.py
- modules/s3db/cap.py
- static/formats/cap/export.xsl
- static/formats/cap/import.xsl
- static/formats/s3csv/cap/info.xsl
> CAP: fix key-value widget import + import/export cleanup + removed cap_info_labels function

- controllers/cap.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/auth_roles.csv
- modules/templates/SAMBRO/controllers.py
- modules/templates/SAMBRO/views/index.html
- static/formats/s3csv/cap/warning_priority.xsl
- static/themes/SAMBRO/style.css
> SAMBRO: warning_priority refactored + filtered options for S3OptionsFilter + SAMBRO: rss icon to the homepage

- languages/tr.py
- modules/s3db/dvr.py
change some translations
move dvr_need define before dvr_case
Conflicts:
languages/tr.py
modules/s3db/dvr.py
> change label name

- controllers/cap.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/views/index.html
- static/formats/cap/export.xsl
- static/scripts/S3/s3.cap.js
- static/themes/SAMBRO/style.css
> SAMBRO:remove blank lines from HTML + add the text back to the label + CAP: update, cancel and clear msg type

- controllers/cap.py
- modules/s3cfg.py
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/views/index.html
> SAMBRO: deployment_settings for msg_type field + minor tweaks

- controllers/cap.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/auth_roles.csv
- static/formats/rss/modules/cap.xsl
> CAP: Avoid msg_type button regression + link to cap file + small bug fix

- controllers/cap.py
- controllers/pr.py
- modules/s3/s3aaa.py
- modules/s3db/pr.py
- modules/templates/SAMBRO/auth_roles.csv
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/controllers.py
- modules/templates/SAMBRO/menus.py
> SAMBRO: admin subscriptions

- controllers/cap.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/controllers.py
- modules/templates/SAMBRO/menus.py
- static/styles/S3/cap.css
> SAMBRO: minor enhancements

- controllers/cap.py
- modules/templates/SAMBRO/controllers.py
> SAMBRO: user_info API

- static/scripts/S3/s3.gis.js
- static/scripts/S3/s3.ui.locationselector.js
@flavour distance verified with http://kml4earth.appspot.com/circlegen.html
Please merge
> gis: circle tool fix

- modules/s3db/cap.py
- static/scripts/S3/s3.ui.locationselector.js
> CAP: cap_resource image upload

- modules/templates/SAMBRO/controllers.py
> SAMBRO: show unexpired alerts on map => match the alerts with the datalist

- controllers/cap.py
- modules/s3db/cap.py
- modules/s3db/doc.py
- modules/templates/000_config.py
- modules/templates/SAMBRO/Demo/Myanmar-Flood-MultiLanguage_MultipleArea.xml
- modules/templates/SAMBRO/Demo/Myanmar_Flood_Multiple_Area.xml
- modules/templates/SAMBRO/Demo/msg_rss_channel.csv
- modules/templates/SAMBRO/Demo/tasks.cfg
- modules/templates/SAMBRO/config.py
- static/styles/S3/cap.css
- static/themes/default/gis.css
> CAP: link area and resource only to alert; info_id kept for importing alert

- controllers/cap.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/controllers.py
- static/scripts/S3/s3.cap.js
> SAMBRO: filter pvt alert and send to pvt group

- controllers/cap.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/Demo/Maldives-Tsunami-MultiLanguage.xml
- modules/templates/SAMBRO/Demo/Myanmar-Flood-MultiLanguage.xml
- modules/templates/SAMBRO/Demo/Myanmar-Flood-MultiLanguage_MultipleArea.xml
- modules/templates/SAMBRO/Demo/Myanmar-Tsunami-MultiLanguage.xml
- modules/templates/SAMBRO/Demo/Philippines-Tropical-Cyclone-MultiLanguage.xml
- modules/templates/SAMBRO/Demo/Philippines-Tsunami.xml
- modules/templates/SAMBRO/auth_roles.csv
- modules/templates/SAMBRO/menus.py
> SAMBRO: notify alert approver regarding aprroval + tweaks

- controllers/cap.py
- modules/s3cfg.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/PH/config.py
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/controllers.py
- static/formats/cap/export.xsl
> CAP: create location from geocode SAME + separate function for area and resource component

- controllers/cap.py
- modules/s3/s3notify.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/MM/auth_roles.csv
- modules/templates/SAMBRO/MM/tasks.cfg
- modules/templates/SAMBRO/auth_roles.csv
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/controllers.py
- modules/templates/SAMBRO/views/msg/notify_email_html.html
- modules/templates/SAMBRO/views/msg/notify_sms.html
> SAMBRO: subscription fixes + SAMBRO: MM editors can create template  + CAP:tweaks

- modules/s3db/cap.py
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/controllers.py
> SAMBRO: bugfix

- controllers/cap.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/menus.py
- modules/templates/SAMBRO/views/msg/notify_sms.html
> SAMBRO: CAP History Model + SAMBRO: fixes

- controllers/cap.py
- controllers/msg.py
- models/tasks.py
- modules/gcm.py
- modules/s3/s3msg.py
- modules/s3db/msg.py
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/controllers.py
- modules/templates/SAMBRO/menus.py
> SAMBRO: gcm for mobile client + SAMBRO: fixes

- controllers/cap.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/Demo/msg_rss_channel.csv
- modules/templates/SAMBRO/config.py
> SAMBRO: tweaks

- modules/templates/SAMBRO/config.py
- static/formats/rss/modules/cap.xsl
> SAMBRO: edit rss description

- controllers/cap.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/config.py
- static/scripts/S3/s3.cap.js
> SAMBRO: handle multiple info in profile + SAMBRO:tweaks

- controllers/cap.py
- modules/s3db/cap.py
> SAMBRO: edit approval message + SAMBRO: fix translation problem + SAMBRO: tweaks

- controllers/cap.py
- modules/s3cfg.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/auth_roles.csv
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/controllers.py
- modules/templates/SAMBRO/views/msg/notify_email_html.html
- modules/templates/SAMBRO/views/msg/notify_sms.html
> SAMBRO: message acknowledgement link for reponders + SAMBRO: use update policy for notification + SAMBRO: tweaks

- controllers/cap.py
> SAMBRO: added check on urgency, severity and certainty

- controllers/cap.py
- modules/s3/s3msg.py
- modules/s3db/cap.py
- modules/s3db/msg.py
- modules/templates/SAMBRO/MM/config.py
- modules/templates/SAMBRO/MV/config.py
- modules/templates/SAMBRO/PH/config.py
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/parser.py
> SAMBRO: fix CAP RSS Feed import

- controllers/cap.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/auth_roles.csv
- modules/templates/SAMBRO/cap_alerting_authority.csv
- modules/templates/SAMBRO/tasks.cfg
- static/formats/s3csv/cap/alerting_authority.csv
- static/formats/s3csv/cap/alerting_authority.xsl
> SAMBRO: start with alerting authority model

- modules/templates/SAMBRO/MM/config.py
- modules/templates/SAMBRO/MV/config.py
- modules/templates/SAMBRO/PH/config.py
- modules/templates/SAMBRO/config.py
> SAMBRO: minor tweaks

- controllers/cap.py
- modules/s3/s3msg.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/config.py
> first step for sending CAP file as attachment in email

- modules/s3/s3utils.py
- modules/s3db/cap.py
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/controllers.py
- modules/templates/SAMBRO/menus.py
> SAMBRO: fixes

- modules/s3/s3msg.py
- modules/s3/s3notify.py
- modules/s3cfg.py
- modules/s3db/pr.py
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/controllers.py
> SAMBRO: subscription form allows the choice of attachment, send attachment from s3notification and implement same in SAMBRO

- modules/s3db/cap.py
- modules/templates/SAMBRO/config.py
- modules/templates/SAMBRO/controllers.py
> small changes in the email alert

- modules/templates/WACOP/controllers.py
Added classes to prepare for design overhaul and removed some minor issues from the data list elements.
> WACOP data list item layout alignment

- static/themes/WACOP/foundation/foundation.css
- static/themes/WACOP/foundation/foundation.rtl.css
- static/themes/WACOP/scss/_settings.scss
- static/themes/WACOP/scss/custom/_mixins.scss
- static/themes/WACOP/scss/custom/_wacop.scss
- static/themes/WACOP/scss/style.scss
- static/themes/WACOP/style.css
Set up base SASS configuration for WACOP project and added styling for alert & event cards.
> wacop sass theme foundation

- modules/templates/WACOP/controllers.py
- static/themes/WACOP/scss/custom/_jquery-ui.scss
- static/themes/WACOP/scss/custom/_mixins.scss
- static/themes/WACOP/scss/custom/_wacop.scss
- static/themes/WACOP/scss/style.scss
- static/themes/WACOP/style.css
jquery-ui first pass
Jquery UI sass variables added
Taggit style
Widget minor adjustments
Tagit margins
Filter multiselect max width
> WACOP comment, tagit, and jQuery UI styling

- modules/s3cfg.py
- modules/s3db/cap.py
- modules/templates/000_config.py
- modules/templates/SAMBRO/config.py
@flavour Please merge
Reference to issue: https://github.com/sahana/SAMBRO/issues/72
> CAP message identifier tweaks

- controllers/cap.py
- modules/s3db/cap.py
> multiple info blocks not allowed for same language

- modules/templates/WACOP/controllers.py
- modules/templates/WACOP/views/event_browse.html
- modules/templates/WACOP/views/incident_browse.html
- modules/templates/WACOP/views/resource_browse.html
- modules/templates/WACOP/views/updates_directories.html
- static/themes/WACOP/js/resize_map.js
- static/themes/WACOP/scss/custom/_wacop.scss
- static/themes/WACOP/style.css
Style all tabs on profile pages
Added tab datalists to browse pages
Added staff and org tabs to top level
resource page clearfix
Set map min height to 400
Minimum height on alert and event boxes content
> WACOP map, alerts, tabs, and clearfix

- modules/templates/WACOP/controllers.py
- modules/templates/WACOP/views/dashboard.html
- modules/templates/WACOP/views/updates_directories.html
- static/themes/WACOP/foundation/foundation.css
- static/themes/WACOP/foundation/foundation.rtl.css
- static/themes/WACOP/scss/_settings.scss
- static/themes/WACOP/scss/custom/_wacop.scss
- static/themes/WACOP/style.css
Dashbord drop down function
Minor fixes
> WACOP: Dashboard first pass

- modules/s3menus.py
Allow to manually import schools via menu.
> Edu: Add menu item to import schools

- Dockerfile
- controllers/msg.py
- modules/s3/s3msg.py
- optional_requirements.txt
- static/formats/s3csv/edu/school.xsl
As briefly discussed on [google groups](https://groups.google.com/forum/#!topic/sahana-eden/Lr9M5z8tdbo), this PR
- Allows Twitter accounts to be created/edited/deleted via admin interface
- ~~Allows tweets to have 280 chars (new feature test-driven by Twitter nowadays)~~
- Smuggles forgotten documentation for #1395
- Updates TwitterSearch requirement to version 1.0+
> Twitter: Allow creation/deletion via admin

- modules/s3db/asset.py
A PR to fix issue reported in #1405
Basically, the variables formerly passed via GET are now implied (hardcoded) based on the method used
- `setbase` = `/asset/asset/1/log/create?status=1`
- `assignperson` = `/asset/asset/1/log/create?status=2&type=person`
- `assignsite` = `/asset/asset/1/log/create?status=2&type=site`
- `assignorg` = `/asset/asset/1/log/create?status=2&type=organisation`
The `type` variable is removed altogether as the intended relation type is now inferred from the method. This also allowed a slight change in the condition logic in `asset_log_onaccept()` where the person assignment is now the default option in `ASSET_LOG_ASSIGN` branch unless explicitly stated otherwise via appropriate method.
I'm not aware of any other module where custom methods would be use in the …
> Asset: Fix assignment errors, remove usage of GET variables

- modules/templates/WACOP/controllers.py
- modules/templates/WACOP/views/group_browse.html
- modules/templates/WACOP/views/group_profile.html
- static/themes/WACOP/scss/custom/_wacop.scss
- static/themes/WACOP/style.css
added base HTML to group views
> WACOP: Group profile and browse view created

- static/formats/cap/export.xsl
also wondering how to debug xslt in the eclipse. is that even possible? too much of effort to debug xslt.
> comment the old way of xslt

- modules/templates/WACOP/controllers.py
- modules/templates/WACOP/views/incident_browse.html
- modules/templates/WACOP/views/incident_profile.html
- modules/templates/WACOP/views/index.html
- modules/templates/WACOP/views/resource_browse.html
- static/themes/WACOP/scss/custom/_wacop.scss
- static/themes/WACOP/style.css
moved read more on event box
Fixed map on home page
removed event/alert boxes
Conditional address data on incident profile
Missing address handling for alert and event html
Tagit visual improvement
Removed list style from update comments
> WACOP: style updates, map fix, and empty address handling

- modules/s3db/supply.py
Given #1475, I believe this is all that remains for fixing #1465. Let me know if there's anything else I should add/change/remove from this PR!
> Fix #1465, supply model validation

- modules/s3db/budget.py
- modules/s3db/dvr.py
- modules/s3db/hrm.py
- modules/s3db/inv.py
- modules/s3db/member.py
- modules/s3db/project.py
- modules/s3db/req.py
- modules/s3db/supply.py
- modules/s3db/work.py
> Allow custom decimal separator in input and representation

- modules/templates/WACOP/controllers.py
- static/themes/WACOP/foundation/foundation.css
- static/themes/WACOP/foundation/foundation.rtl.css
- static/themes/WACOP/scss/_settings.scss
- static/themes/WACOP/style.css
set max width 1400 fixes #27
removes button classes from elements
> WACOP: minor style updates

- modules/templates/SAMBRO/AlertHub/config.py
- modules/templates/SAMBRO/AlertHub/msg_rss_channel.csv
> SAMBRO AlertHub minor fixes to pre-pop rss import and language codes

- modules/s3db/cms.py
> Don't URLise CMS content if <a> tags already exist

- modules/unit_tests/s3db/cms.py
These tests complement the logic added in #1515
> Add tests for the represent method on the cms_post.body field

- modules/templates/SAMBRO/controllers.py
> SAMBRO: Display error DIV if map layer is missing

- modules/s3/s3widgets.py
- modules/s3db/gis.py
- static/scripts/S3/s3.autocomplete.js
And specify that organisations can be part of the autocomplete as well.
Fixes #1425
> Use S3PentityAutocompleteWidget for "Person or OU" field in map profile

- languages/th.py
Sungkom Piamviriyawong : Change 'This email address is already in use' to suitable meaning
> Sungkom Piamviriyawong : Change 'This email address is already in use' to suitable meaning fof th.py

- modules/templates/SAMBRO/AlertHub/msg_rss_channel.csv
- modules/templates/SAMBRO/Demo/msg_rss_channel.csv
On 2020-04-02, *ptwc.weather.gov* domain has been terminated (see announcement on https://twitter.com/NWS_PTWC/status/1245501200587341824 ). There are a few SAMBRO feeds which used it. SAMBRO template setup now fails with the traceback given below.
This PR replaces the obsolete feeds with the new one from *tsunami.gov*.
```
Importing SAMBRO/Demo...
2020-04-04 12:46:25 S3LOG DEBUG: organisation.csv imported (0.12 sec)
2020-04-04 12:46:25 S3LOG DEBUG: users.csv imported (0.20 sec)
2020-04-04 12:46:25 S3LOG DEBUG: import_user completed (0.20 sec)
2020-04-04 12:46:25 S3LOG DEBUG: gis_config.csv imported (0.06 sec)
2020-04-04 12:46:25 S3LOG DEBUG: cap_warning_priority.csv imported (0.09 sec)
2020-04-04 12:46:25 S3LOG DEBUG: cap_alert.csv imported (0.07 sec)
2020-04-04 12:46:25 S3LOG DEBUG: …
```
> Replace obsolete PTWC feeds in SAMBRO imports

- static/formats/s3csv/org/organisation.csv
- static/formats/s3csv/org/organisation.xsl
(Starting with something simple to get an idea how the imports work.)
This PR adds the option to import year the organization was founded, as discussed in #1554.
> Org: Allow year to be imported

- Dockerfile
Reference commit: beb979ffafea38af31919746b2a69fd30cdda605
> Fix Dockerfile with update path of 000_config.py
